---
title: "Ecosystem Considerations"
author: "E. Siddon"
date: "2024-11-04"
output: html_document
---

*Environmental processes*: The eastern Bering Sea (EBS) experienced a prolonged period of above-average thermal conditions from 2014 through 2021. Since 2021, and continuing from August 2023–August 2024, thermal conditions in the EBS have been close to historical baselines of many metrics. There have been no sustained marine heatwaves over the southeastern or northern Bering Sea shelves since January 2021 (@Callahan2024), and observed (Rohan and Barnett, 2024) modeled (@Kearney2024) EBS bottom temperatures were mostly near-normal over the past year. Sea surface temperatures (SSTs) and bottom temperatures were near the long-term means in all regions by summer 2024. Notable deviations include (i) warm SSTs in the outer domain from fall 2023 through spring 2024 and (ii) unusually warm bottom temperatures in the northern outer domain since spring 2024 that may indicate an intrusion of shelf water (@Callahan2024).
Atmospheric conditions are one of the primary drivers that impact the oceanographic setting in the EBS. Both the North Pacific Index (NPI) and Aleutian Low Index (ALI) provide complementary views of the atmospheric pressure system in the North Pacific. During winter 2023-2024, the NPI was average (Siddon, 2024) and the strength and location of the Aleutian Low Pressure System were both near climatological averages (Overland and Wang, 2024). Thus, despite delayed formation of sea ice in fall 2023 (Thoman, 2024), cold winds from the Arctic helped advance sea ice to near-normal extent by mid-winter. Near-normal sea ice extent and thickness (Thoman, 2024b, 2024c) may have contributed to a cold pool (<2°C water) of average spatial extent (Siddon, 2024), though the footprint of the coldest waters (<0°C) in 2024 was 75% smaller than in 2023 (Rohan and Barnett, 2024b). 

FHS is a winter-spawning flatfish; increased young-of-the-year recruitment is correlated to years with onshore winds during the larval period. The along- and cross-slope wind components along the Bering shelf break may be informative to understanding the larval dispersal in the upper ocean. December 2023 had significant along-shelf winds (to the southeast) that could have driven offshore Ekman transport. Weaker, but more sustained winds that also favored offshore transport occurred from March to May 2024 (Hennon, 2024), which overlaps with the FHS larval period. In the 2024 bottom trawl survey, FHS biomass increased 22% from 2023 to 2024 while abundance increased 13%.
For projections into 2025, the National Multi-Model Ensemble (NMME) predicts that SSTs over the EBS are expected to be near normal (anomalies within <0.5°C of the 1982–2010 baseline) (Lemagie, 2024). With the expected transition to La Niña, cooler conditions in the EBS may follow. Relatively cool SSTs may contribute to earlier formation of sea ice than has been observed over the last several years (Thoman, 2024b).
Metrics of ocean acidification include $\Omega$arag and pH. Summer 2024 bottom water $\Omega$arag conditions were similar to 2023 while pH was slightly more acidic; the most corrosive bottom waters were found in slope waters and over the northwest shelf (Pilcher et al., 2024). 


*Prey*: Prey resources for adult FHS and Bering flounder include brittle stars (echinoderms), polychaetes, and crustaceans as well as juvenile walleye pollock. Trends in motile epifauna biomass indicate benthic productivity, although individual species and/or taxa may reflect varying time scales of productivity. The biomass of motile epifauna increased from 2023 to 2024 and remains above the long term mean (Siddon, 2024). No direct or indirect measures of prey availability exist for the northern Bering Sea shelf. 
The estimated abundance of larval pollock sampled in spring increased from near the end of the last cold stanza (2012) through the warm stanza (2014, 2016, 2018) to a time-series maximum in 2024 (Rogers et al., 2024). By late summer, age-0 pollock CPUE estimates in the middle domain of the SEBS and NBS regions were lower than estimates from the recent warm period (2014–2021) but slightly higher than estimates from the cold period (2007–2013). In the inner domain, pollock were the most numerous non-salmonid species collected in the ADF&G nearshore survey (Garcia et al., 2024). In the NBS, CPUE estimates have remained low compared to the SEBS (Andrews et al., 2024). Since 2022, with cooler SSTs, pollock weights and energy density have been low while % lipid has been average (Page et al., 2024).
The condition of FHS (as measured by length-weight residuals) over the SEBS remains near average (Prohaska et al., 2024), indicating sufficient prey may be available.

*Competitors*: Competitors of FHS prey resources include other benthic foragers, like northern rock sole and yellowfin sole. The trend in biomass of the benthic foragers guild from the standard bottom trawl survey grid increased from 2023 to 2024. Flathead sole, northern rock sole, and yellowfin sole all contributed to the increase. However, both NRS and YFS remain below their long term means and the guild remains below the time series mean. Trends in benthic forager biomass indirectly indicate availability of infauna (i.e., prey of these species), suggesting competition for prey resources remains low in 2024 (Siddon, 2024).


*Predators*: Predators of FHS include Pacific Cod, Arrowtooth flounder, Greenland turbot, halibut, and pollock. In terms of predation pressure on FHS, we focus on biomass trends over the southern Bering Sea shelf. The biomass within the apex predator guild (including Pacific cod, Arrowtooth flounder, Greenland turbot, and halibut) measured during the standard bottom trawl survey in 2024 was nearly equal to their value in 2023 and below their long term mean (Siddon, 2024). Within that guild, Pacific cod and Pacific halibut biomass declined while arrowtooth flounder increased 26% from 2023 to 2024 (Siddon, 2024). Pollock biomass in the EBS increased substantially from 2023 to 2024 (78% increase of pollock in the pelagic forager guild; Siddon, 2024), largely as a result of the 2018 year class. Taken together, trends in competitors indicate potentially increased predation pressure for FHS. 

Together, the most recent data available suggest an ecosystem risk Level 1 – Normal: “No apparent ecosystem concerns related to biological status (e.g., environment, prey, competition, predation), or minor concerns with uncertain impacts on the stock.”


# References:
Andrews, A., E. Yasumiishi, A. Spear, J. Murphy, and A. Dimond. 2024. Catch Estimates of Age-0 Walleye Pollock from Surface Trawl Surveys, 2003–2024. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Callahan, M., and E. Lemagie. 2024. Bering Sea SST anomalies. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Callahan, M., K. Kearney, and E. Lemagie. 2024. Bering Sea SST and Bottom Temperature Trends. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Garcia, S., K. Howard, and B. Gray. 2024. Alaska Department of Fish & Game Nearshore Survey. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Hennon, T. 2024. Winds at the Shelf Break. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Kearney, K. 2024. Cold Pool Extent - ROMS. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Lemagie, E. 2024. Seasonal Projections from the National Multi-Model Ensemble (NMME). In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Overland, J. and M. Wang. 2024. Wintertime Aleutian Low Index. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Page, J., J. Maselko, R. Suryan, T. Miller, E. Siddon, E. Fergusson, C. Mattson, A. Masterman, and B. Cormack. 2024. Fall Condition of Young-Of-The-Year Walleye Pollock in the Southeastern and Northern Bering Sea, 2002–2024. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Pilcher, D., J. Cross, N. Monacci, E. Kennedy, E. Siddon, and W.C. Long. 2024. Ocean Acidification. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Prohaska, B., R. Howard, and S. Rohan. 2024. Eastern and Northern Bering Sea Groundfish Condition. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Rogers, L., K. Axler, W. Fennie, L. Nave-Powers, B. Snyder, and N. Roberson. 2024. Abundance and Distribution of Larval Fishes in the Southeastern Bering Sea 2012–2024. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Rohan, S., and L. Barnett. 2024. Summer Temperatures. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Rohan, S., and L. Barnett. 2024b. Cold Pool Extent - AFSC Bottom Trawl Survey. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Siddon, E. 2024. Southeastern Bering Sea Report Card. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Thoman, R.. 2024. Early Season Ice Extent. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Thoman, R. 2024b. Bering Sea Daily Ice Extent. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

Thoman, R. 2024c. Sea Ice Thickness. In: Physical Environment Synthesis. In: Siddon, E. 2024. Ecosystem Status Report 2024: Eastern Bering Sea, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West 3rd Ave., Suite 400, Anchorage, Alaska 99501.

