# Executive Summary

“Flathead sole” as currently managed by the North Pacific Fishery Management Council (NPFMC) in the Bering Sea and Aleutian Islands (BSAI) represents a two-species complex consisting of true Flathead sole (Hippoglossoides elassodon) and its morphologically-similar congener Bering flounder (Hippoglossoides spp.). In 2012, the BSAI Groundfish Plan Team moved Flathead sole to a biennial stock assessment schedule because it has historically been lightly exploited. A full stock assessment report was most recently produced in 2020 (Monnahan and Haehn, https://apps-afsc.fisheries.noaa.gov/refm/docs/2020/BSAIflathead.pdf). A full assessment for BSAI Flathead sole was scheduled for 2022, but due to limited staff resources, a partial assessment is presented this year. In partial assessment years, an executive summary is presented to recommend harvest levels for the next two years, along with trends in catch and biomass.

Flathead sole is assessed using an age-structured model and Tier 3 determination. The single species projection model is run using parameter values from the accepted 2020 assessment model, together with updated catch information for `r paste0(range(2020,year-1),collapse='-')` and estimated catches for `r year` and `r paste0(range(year+1,year+2),collapse='-')` (Figure \@ref(fig:fig1)), to predict stock status for Flathead sole in `r paste0(range(year+1,year+2),collapse='-')`, and to make ABC recommendations and set OFL for those years.

## Summary of Changes in Assessment Inputs

This assessment used a single survey index of “total” Hippoglossoides spp. biomass that included the EBS “standard” survey areas and AI survey areas for the years 1982-2019 (Table \@ref(tab:tab2)). As was done in the 2020 full assessment (Monnohan et. al. 2020) and the 2022 partial assessment (Kapur 2021), we estimated a relationship between EBS shelf Hippoglossoides spp. survey biomass estimates and AI survey biomass estimates in years when no AI survey occurred. The estimation method uses the linear regression to find an AI biomass estimate in a particular year based on the EBS biomass estimate for that year. There were no AI surveys conducted in 2020 nor 2021, and AI biomass for those years was estimated with the linear equation. An Aleutian Islands survey was conducted in 2022, and the 2022 total BSAI estimate was 710,804 t, a roughly 6% increase over the 2021 regression estimate of 670,091 t (Figure \@ref(fig:fig2)).

To run the projection model to predict ABCs for `r year+1` and `r year+2`, we used true, observed catches for `r paste0(range(2020,year-1),collapse='-')` and estimates for the total catches in `r paste0(range(year,year+2),collapse='-')`. Note that the 2020 catch used in the last benchmark model was itself an estimate (8,556), about 9% less than the finalized observation used for projections here. The catch for `r year` (`r prettyNum(catchvec[4,2],big.mark=',')` t) was estimated by adding the average catch between Sep 27 and December 31 over the years `r paste0(range(year-6,year-1),collapse='-')` to the `r year` catch as of Sep 27, 2022. The `r year+1` and `r year+2` catches (`r prettyNum(catchvec[5,2],big.mark=',')` t) were estimated as the average catch over the previous 5 years (`r paste0(range(year-6,year-1),collapse='-')`).

To ensure consistency with the most recent full assessment (Monnohan and Haehn, 2020), the projection model was parameterized using mean recruitment and stock spawning biomass for all years included in the assessment model (1964 onwards). Future full assessments for BSAI Flathead sole can consider updating these inputs in light of the determination of a regime shift in 1977, and subsequent recommendation that projections of future stock states should be based on year classes 1977 and forward.

