## Flathead sole and Being flounder combined. I changed this from
## the GET_CATCH query, adding some columns that are used in
## later reports.
qcatch <- paste("SELECT SUM(COUNCIL.COMPREHENSIVE_BLEND_CA.WEIGHT_POSTED) AS TONS,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA AS ZONE,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR AS GEAR,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.RETAINED_OR_DISCARDED AS TYPE,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR AS YEAR,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE AS NMFS_AREA,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_NAME AS SPECIES,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.CDQ_FLAG AS CDQ\n",
        "FROM COUNCIL.COMPREHENSIVE_BLEND_CA\n ",
        "WHERE COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA in (",fsh_sp_area,")\n ",
        "AND COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR <= ",final_year,"\n ",
        "AND COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_GROUP_CODE in (",fsh_sp_label,")\n ",
        "GROUP BY COUNCIL.COMPREHENSIVE_BLEND_CA.SPECIES_NAME,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_SUBAREA,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.FMP_GEAR,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.REPORTING_AREA_CODE,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.RETAINED_OR_DISCARDED,\n ",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.CDQ_FLAG,\n",
        "COUNCIL.COMPREHENSIVE_BLEND_CA.YEAR\n ", sep="")