# References

Kapur, M.S. 2022. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. In Stock Assessment and Fishery Evaluation Report for the Groundfish Resources of the Bering Sea/Aleutian Islands Region. North Pacific Fishery Management Council, P.O. Box 103136, Anchorage, Alaska 99510. Available at https://apps-afsc.fisheries.noaa.gov/Plan_Team/2022/BSAIflathead.pdf.

Kapur, M.S. 2021. Assessment of the Flathead Sole-Bering flounder Stock in the Bering Sea and Aleutian Islands. In Stock Assessment and Fishery Evaluation Report for the Groundfish Resources of the Bering Sea/Aleutian Islands Region. North Pacific Fishery Management Council, P.O. Box 103136, Anchorage, Alaska 99510. Available at https://apps-afsc.fisheries.noaa.gov/refm/docs/2021/BSAIflathead.pdf.

Monnahan, C., and Haehn, R. 2020.Assessment of the Flathead sole-Bering flounder stock complex in the Bering Sea and Aleutian Islands. In Stock Assessment and Fishery Evaluation Report for the Groundfish Resources of the Bering Sea/Aleutian Islands Region. North Pacific Fishery Management Council, P.O. Box 103136, Anchorage, Alaska 99510. Available at https://apps-afsc.fisheries.noaa.gov/refm/docs/2020/BSAIflathead.pdf
