---
params: 
  chapter: 10
  species: "Flathead sole-Bering flounder"
  species_complex: "no"
  area: "Bering Sea and Aleutian Islands"
  tier: 3

author: "Maia S. Kapur"
date: "November 2023"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::word_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---

```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
```

```{r}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock complex in the ", params$area)  
  }


```

---
title: `r title`
---

```{r load, warning=F, message=F}
# load
library(safe)
library(dplyr)
# globals
species = params$species
this_year = 2023
date = 'October 22, 2023'
pull_date = "2023-09-27"
model = "base"
end_proj = this_year + 15
best_f = 0.0641 # from the best_f function in groundfishr package

ofl_24<-81605
ofl_25<-82699
abc_24<-67289
abc_25<-67203

ofl_24_22 <-81167
abc_24_22 <-66927

load(here::here(this_year,'data', paste0("2023-09-27-catches_for_proj.rdata")))
c1 = as.numeric(catchvec[4,2]) # estimated catch in current year
c2 = as.numeric(catchvec[5,2]) # proj catch year + 1
c3 = as.numeric(catchvec[6,2]) # proj catch year + 2
```

```{r, child="01-summary.Rmd", eval = T}
```


\newpage

```{r, child="11-tables.Rmd", eval = T}
```

```{r, child="12-figures.Rmd", eval = T}
```

```{r, child="13-references.Rmd", eval = T}
```


