---
editor_options: 
  markdown: 
    wrap: sentence
---
\newpage

# Data

> Operational Update: The data description for Flathead sole-Bering flounder has been truncated to highlight relevant updates or changes made for this cycle. The reader is referred to the last full assessment [@Monnahan2020] for the entirety of this section. 

The following table summarizes the data used for this assessment.

```{r}

data.frame(Source = c(rep("NMFS Aleutian Islands Groundfish Trawl Survey", 1),
                      rep("NMFS Bering Sea Shelf Groundfish Survey (standard survey area only; excludes survey strata 70, 81, 82, 90, 140, 150, and 160)", 3),
                      rep("U.S. trawl fisheries",3),
                      "Foreign trawl fisheries in the BSAI"),
           Data = c("Survey biomass (linear regression used to combine BS shelf survey estimates with AI survey estimates for a single survey biomass index)",
                    "Survey biomass (linear regression used to combine BS shelf survey estimates with AI survey estimates for a single survey biomass index)                        ",
                    "Conditional age-at-length composition", 
                    "Marginal length composition",
                    "Catch (pelagic and non-pelagic trawl in the Bering Sea and Aleutian Islands; a very small amount of catch is taken with hook and line and is included in the total catch biomass)",
                    "Marginal age composition (Bering Sea only; non-pelagic trawl only)",
                    "Marginal length composition (Bering Sea only; non-pelagic trawl only)",
                    "Catch (Bering Sea and Aleutian Islands; trawl)"),
           Species = c("Flathead only; no Bering flounder were caught in the Aleutian Islands",
                       "Flathead sole and Bering flounder combined",
                       "Flathead sole only", 
                       "Flathead sole only",
                       "Flathead sole and Bering flounder combined",
                       "Flathead sole only",
                       "Flathead sole only",
                       "Flathead sole and Bering flounder combined"),
           Years = c("1983, 1986, 1991-2000 (triennial), 2002-2006 (biennial), 2010-2022 (biennial)",
                     "1982-2019, 2021-2024",
                     "1982, 1985, 1992-1995, 1999-2019, 2021-2023", 
                    "1982-2019, 2021-2024",
                    "1963-2024 (final year is estimated)",
                    "2000, 2001, 2004-2007,2009-2021",
                    "1977-1999, 2002-2003, 2008, 2020-2023",
                    "1964-1987"))  %>% 
  flextable::flextable() %>% 
  flextable::width(j = ~ Source, width = 1) %>% 
  flextable::width(j = ~ Species, width = 1.5) %>% 
  flextable::width(j = ~ Data, width = 1.5) %>% 
  flextable::width(j = ~ Years, width = 2.5) %>% 
  flextable::merge_v(j = 1) %>% 
  flextable::font(fontname = "Times", part = "all") %>% 
  flextable::fontsize(size = 10) %>% 
  flextable::theme_vanilla() %>% 
  flextable::fix_border_issues()  %>%
  flextable::footnote(
  x = ., i = 6:7, j = 2,
  ref_symbols = "*",
  value = flextable::as_paragraph("To avoid double-counting data used to estimate parameters in the assessment model, the size composition data were excluded in the model optimization when the age composition data from the same year were available. Thus, only the flathead sole fishery size compositions for 1977-1999, 2002-2003, 2008, 2022 and 2023 were included.")
)


```


## Fishery

Catches as used in the model are shown in Table 9.\@ref(tab:catches); discards are not used in the model. Fishery-dependent compositional data (catch-at-length and catch-at-age, and associated input sample sizes) are shown in Tables 9.\@ref(tab:fishlengthcompstF) through 9.\@ref(tab:fishagecompstM). The model uses an estimate of 2024 catch to be consistent with the projection routine.

## Survey

Survey biomass estimates and associated sampling variability (annual CVs) are shown in Table 9.\@ref(tab:survobs). Survey length compositional data are shown in Tables 9.\@ref(tab:survlengthcompsF) and 9.\@ref(tab:survlengthcompsM). Survey conditional age-at-length data is prohibitively large to present in this document; readers may access these data electronically [here](https://github.com/afsc-assessments/bsai-fhs/blob/bafa7658d31e0b99fe11d626a58e1c01807c69ee/2024/mgmt/18.2c_2024/2020_BSAI_FHS.dat#L277).

This assessment updated the input sample sizes for all survey compositional datasets (marginal lengths and conditional ages-at-length [CAAL], as well as those for marginal ages which are not included in the joint likelihood). The previous approach used the number of hauls as the input sample size for marginal lengths, and the nominal number of read otoliths as the input sample size for CAAL data. 