# Selected Model Results

> Operational Update: This section has been condensed to follow the newest guidelines for "Operational Update Assessments" to the best of the Authors' ability. A minimal set of figures and tables are provided here; links to electronic files for supplementary data (e.g., numbers-at-age from the base model) are included in-text.

The model used in this assessment is the same as the model accepted in 2020 (`r old_model_name`) with updated data and parameter priors. Model `r old_model_name` with data updated through `year` generally results in reasonable fits to the data, estimates biologically plausible parameters, and produces consistent patterns in abundance compared to previous assessments. 

## Model Evaluation

### Residual Analysis and Convergence Criteria

The model achieved convergence as defined by an invertible Hessian matrix and a low maximum gradient component (less than`1e-4`) that was achieved using the `hess_step` function in ADMB. Time-series plots of observed and predicted values, and the time-series of recruitment deviations, did not suggest unusual residual patterns, or different behavior than in previous assessments. The uncertainty around parameter estimates (obtained via MCMC, see below) and related derived quantities were in line with previous models.

### Parameter Estimates and Parameter Uncertainty 

Table \@ref(tab:parposteriorst) lists all estimated parameters in the base model. It includes the associated asymptotic standard error estimates or other statistical measures of uncertainty.  Time series of deviation parameters (fishing mortality rates $F$ and recruitment deviations from (`r paste0(mod18.2c_2024$startyr,'-',mod18.2c_2024$endyr)`)) are shown in Figures \@ref(fig:biofreccompare) and \@ref(fig:recdevs), respectively.
 
From the MCMC chains described in [Model Uncertainty](#modeluncertainty), we summarize the posterior densities of key parameters for the recommended model using histograms (Figure \@ref(fig:hists)) and credible intervals (Table \@ref(tab:parposteriorst)). We also use these posterior distributions to show uncertainty around time series estimates of survey biomass (Figure \@ref(fig:survey)), total and spawning biomass, fully selected fishing mortality and recruitment (Figure \@ref(fig:biofreccompare)).

Table \@ref(tab:parposteriorst) shows the maximum likelihood estimate (MLE) of key parameters with corresponding 95% credible intervals from the MCMC analysis. In 2021, a comparison between standard deviations derived from the Hessian matrix and MCMC indicated that uncertainty estimates were similar for $q$, $M$, and $F_{40\%}$, but the MCMC standard deviations were larger for the estimates of female spawning biomass and ABC. These larger standard deviations indicate that these parameters are more uncertain than indicated by the Hessian approximation. The distributions of these parameters with the exception of natural mortality are slightly skewed with higher means than medians for current spawning biomass and ABC, indicating possibilities of higher biomass estimates (Figure \@ref(fig:biofreccompare)). 

### Time Series Results
*Definitions:* Spawning biomass is the estimated weight of mature females. Total biomass is the estimated weight of all FHS ages 3 and greater. Recruitment is measured as the number of age-zero individuals Fishing mortality is the mortality at the age the fishery has fully selected the fish. 

Key results have been summarized in Table  \@ref(tab:timeseriest). Model predictions generally fit the data well (Figures .\@ref(fig:catch) through 10.\@ref(fig:survey)). A comma-separated electronic file containing the estimated numbers-at-age is available at https://github.com/afsc-assessments/bsai-fhs/blob/main/2024/mgmt/18.2c_2024/natage.csv.

#### Biomass


Spawning biomass was at a low in `r mod18.2c_2024$timeseries[which.min(mod18.2c_2024$timeseries$SpawnBio),'Yr']` of `r prettyNum(mod18.2c_2024$timeseries[which.min(mod18.2c_2024$timeseries$SpawnBio),'SpawnBio'], big.mark = ',')` t, reached a peak in `r subset(mod18.2c_2024$timeseries,Yr > 1980)[which.max(subset(mod18.2c_2024$timeseries,Yr > 1980)$SpawnBio),'Yr']` of `r prettyNum(subset(mod18.2c_2024$timeseries,Yr > 1980)[which.max(subset(mod18.2c_2024$timeseries,Yr > 1980)$SpawnBio),'SpawnBio'], big.mark = ',')` t, slowly decreased through 2020 and recently increased to a current spawning biomass of `r `prettyNum(mod18.2c_2024$timeseries[which.min(mod18.2c_2024$timeseries$SpawnBio),'Yr'], big.mark=','` t in `r year` (Figure \@ref(fig:biofreccompare)). These trends correspond to a period of high recruitment from 1980-1990, a period low recruitment occurred from 2004-2010 (Figure \@ref(fig:recdevs)) and increasing survey observations since 2015 (Figure \@ref(fig:survey)). The survey data are fit well throughout the time series.

#### Fishing Mortality

Historical apical fishing mortality was between `r paste(round(range(mod18.2c_2024$timeseries$`F:_1`[mod18.2c_2024$timeseries$Yr %in% 1978:1987]),3), collapse = ' and ')` for the historical period of foreign fleets and the joint venture fishery. The estimates of uncertainty in fishing mortality during this period are artificially small due to the absence of a stock-recruitment relationship. Fishing mortality reached a peak in `r mod18.2c_2024$timeseries[which.max(mod18.2c_2024$timeseries$`F:_1`),'Yr']` at `r round(mod18.2c_2024$timeseries$`F:_1`[mod18.2c_2024$timeseries$Yr <2005]),3)`, and remained between `r paste(round(range(mod18.2c_2024$timeseries$`F:_1`[mod18.2c_2024$timeseries$Yr %in% 1990:2005]),3), collapse = ' and ')`in the 1990s and early 2000’s. Fishing mortality reached another peak of approximately `r `round(mod18.2c_2024$timeseries[which.max(mod18.2c_2024$timeseries$`F:_1`),'F:_1'],3)` in `r  mod18.2c_2024$timeseries[which.max(mod18.2c_2024$timeseries$`F:_1`),'Yr']`  and has generally declined in recent years since 2008 (Table 9.17). In contrast, the plot of 1-SPR shows that overall fishing intensity was highest during the period of foreign fishing, peaking in 1972 of approximately 0.5. 1-SPR fell to between 0.1 and 0.2 in 1987-1989 and stabilized around or just above 0.2 thereafter. The estimated SPRs over the modeled time period were all well below the management target of 1-SPR = 0.6.

#### Selectivity
Figure 9.15 and Figure 9.16 show the estimated length-based fishery selectivity curves and Figure 9.17 shows the estimated age-based survey selectivity curves for Model 18.2c. The fishery selectivity curves suggest that males were caught at smaller lengths than females. Likewise, the survey selectivity curves are age-based and males and females were caught at similar ages, which means that males were caught at smaller lengths than females because males grow more slowly and not as large as females. This could occur if similar ages of flathead sole (male and female) tend to be caught together. Another reason why this could occur is if there was a consistent bias in sexing the fish, such that smaller fish caught within a haul are more likely to be sexed as male. However, conversations with the survey sampling group indicate that flathead sole are relatively easy to sex as compared to other species. Allowing male selectivity to be different from female selectivity was new in the 2018 model and largely resolved a residual pattern in yearly fits to fishery and survey length composition data that occurred across almost every year modeled and in all of the historical BSAI flathead sole assessments that reported yearly fits to fishery and survey length composition data (Stockhausen et al. 2012, McGilliard et al. 2014, McGilliard et al. 2016). 
The survey sampling group reported finding similar ages of flathead sole within hauls, and this could be explored further in the future by looking at the survey and observer age data at the haul level. Model 18.2c (2020) estimated male and female fishery selectivity curves for the period 1964-1987 that selected fish at substantially smaller lengths than for the current period beginning in 1988. In the early period there were only catch data from 1964-1976, and only length composition and catch data from 1977-1982. The model could estimate a substantially different fishery selectivity curve if length-at-age were different during this early period. However, survey length-at-age data exist beginning in 1982, during this early period, and show no substantial changes in length-at-age over time (Figure 9.6-Figure 9.7). Additionally, the model could estimate a different fishery selectivity curve for the early period if length-at-age were different for fishery data than for survey data. If this were occurring it would likely show up in ghost fits to fishery length composition data in years where fishery age composition data were included in the likelihood instead of fishery length composition data. Fishery age composition data were used in many years from 2000 onward (Figure 9.37), and ghost fits to fishery length composition data in those years were quite good (Figure 9.36), suggesting that for these years, length-at-age in the fishery was similar to length-at-age in the survey (only the survey data was used to inform growth parameters and variability in growth in the model). There were no fishery ages available prior to 2000 to further test this hypothesis, but there was also no indication that length-at-age changed meaningfully over time.


#### Recruitment

Recruitment (as measured by age-2 fish) for POP is highly variable and large recruitment events comprise much of the biomass for future years (Figure \@ref(fig:biofreccompare)). The model estimates that recruitment was below average from 1975-1985 (Figure \@ref(fig:recdevs)), after which it was above average for many years. The survey age data and the large survey biomass observations from 2013 onwards suggest that there were strong year classes in 2008, 2010, 2012, 2014 and 2018 (Figure \@ref(fig:recdevs)). However, these recent recruitment events are still uncertain as indicated by the MCMC credible intervals in Figure \@ref(fig:recdevs), some of which cross the zero (average) line. The high recruitment estimate of 2018 has been revised downwards from the 2021 assessment with the addition of survey and fishery ages through 2021 and 2022, respectively, and is now of a similar scale to earlier estimates.

Flathead sole do not seem to exhibit a stock-recruitment relationship because large recruitment has occurred during periods of high and low biomass (Figure \@ref(fig:biofreccompare) and Table \@ref(tab:timeseriest)). The FHS model does not specify an explicit stock-recruitment relationship. The average annual recruitment (in numbers) spawned after 1976 is estimated to be `r prettyNum(round(1e-6*with(subset(mod18.2c_2024$timeseries, Yr %in% 1977:2024), mean(Recruit_0)),3) big.mark = ',')` million.

### Comparison to Previous Model

A comparison of key derived quantities from the base model and the most recent full assessment is shown in Figure \@ref(fig:biofreccompare).  Parameter estimates and likelihood functions have remained similar to the 2020 model, and the 95% credible intervals of the current parameter estimates encompass the 2020 medians (Figure \@ref(fig:biofreccompare) and Tables \@ref(tab:parposteriorst) and \@ref(tab:resultscompare)).



