---
editor_options: 
  markdown: 
    wrap: sentence
---
 
## Harvest recommendations

> Operational Update: The description of Amendment 56 specifications for POP and details regarding the development of the Risk Table have been truncated to provide minimal background and highlight relevant updates or changes made for this cycle. The reader is referred to the last full assessment [@Hulson2021] for the entirety of this section, including details on the projection approach.


### Amendment 56 Reference Points

POP in the GOA are managed under Tier 3 of Amendment 56. It is assumed that the equilibrium level of recruitment is equal to the average of age-2 recruitments between 1979 and `r year-2` (i.e., the 1977-`r year-4` year classes). The most recent two years of recruitment are not included in the projection due to lack of data that would support these recruitment estimates. This definition of equilibrium recruitment is used to estimate the  $B_{40}$ reference point. Other useful biomass reference points which can be calculated using this assumption are $B_{100}$ and $B_{35}$, defined analogously to $B_{40}$.

Female spawning biomass for `r year+1` is estimated at `r prettyNum(ssb_25,big.mark =',')` t.  This is above  $B_{40}$=`r prettyNum(b40_25,big.mark =',')` t. Under Amendment 56, Tier 3, the maximum permissible fishing mortality for ABC is $F_{40}$ and fishing mortality for OFL is $F_{35}$. The `r year+1` estimates of biomass-based reference points, and the resultant ABC and OFL based on the fishing mortality rates are:


| Reference Point | Description                                                                                                                                                | Value   |
|------------------------|------------------------|------------------------|
| $B_{100\%}$      | The equilibrium spawning biomass that would be obtained in the absence of fishing                                                                          | `r prettyNum(b0_25,big.mark =',')` t |
| $B_{40\%}$       | 40% of the equilibrium spawning biomass that would be obtained in the absence of fishing                                                                   | `r prettyNum(b40_25,big.mark =',')` t |
| $B_{35\%}$       | 35% of the equilibrium spawning biomass that would be obtained in the absence of fishing                                                                   | `r prettyNum(b35_25,big.mark =',')` t |
| $F_{40\%}$       | The fishing mortality rate that reduces the equilibrium level of spawning per recruit to 40% of the level that would be obtained in the absence of fishing | `r prettyNum(Fabc_25,big.mark =',')`    |
| ABC             | Yield at $F_{40\%}$ in 2024                                                                                                                                       | `r prettyNum(abc_25,big.mark =',')` t |
| $F_{35\%}$       | The fishing mortality rate that reduces the equilibrium level of spawning per recruit to 35% of the level that would be obtained in the absence of fishing |`r prettyNum(Fofl_25,big.mark =',')`    |
| OFL             | Yield at $F_{35\%}$  in 2024 | `r prettyNum(ofl_25,big.mark =',')` t  |

### Specification of OFL and Maximum Permissible ABC {#oflabc}

#### Standard Harvest Scenarios (Harvest Projections) {#harvestprojections}

A standard set of projections is required for each stock managed under Tier 3 of Amendment 56. Five of the seven standard scenarios support the alternative harvest strategies analyzed in the Alaska Groundfish Harvest Specifications Final Environmental Impact Statement. They are as follows (“max$F_{ABC}$” refers to the maximum permissible value of $F_{ABC}$ under Amendment 56):

+   *Scenario 1*:  In all future years, $F$ is set equal to max$F_{ABC}$ (Rationale:  Historically, TAC has been constrained by ABC, so this scenario provides a likely upper limit on future TACs.)

+   *Scenario 2*:  In `r year+1` and `r year+2`, $F$ is set equal to a constant fraction of max $F_{ABC}$, where this fraction is equal to the ratio of the realized catches in `r paste0(range(year-3, year-1), collapse='-')` to the ABC (which is generally the same as the TAC) recommended in the assessment for each of those years. For the remainder of the future years, maximum permissible ABC is used. (Rationale:  Using recent catch to ABC ratios will yield more realistic projections for the POP fishery, which rarely realizes its full TAC or ABC). The exact calculation of these values is shown [below](#authorsF).

+   *Scenario 3*:  In all future years, $F$ is set equal to 50% of max $F_{ABC}$. (Rationale:  This scenario provides a lower bound on $F_{ABC}$ that still allows future harvest rates to be adjusted downward when stocks fall below reference levels.)

+   *Scenario 4*:  In all future years, $F$ is set equal to the `r paste0(range(year-6, year-2), collapse='-')` average F. (Rationale:  For some stocks, TAC can be well below ABC, and recent average $F$ may provide a better indicator of FTAC than $F_{ABC}$.)

+   *Scenario 5*:  In all future years, $F$ is set equal to zero. (Rationale:  In extreme cases, TAC may be set at a level close to zero.)

Two other scenarios are needed to satisfy the MSFCMA’s requirement to determine whether a stock is currently in an overfished condition or is approaching an overfished condition. These two scenarios are as follows (for Tier 3 stocks, the MSY level is defined as $B_{35\%}$): 

+   *Scenario 6*:  In all future years, $F$ is set equal to $F_{OFL}$. (Rationale:  This scenario determines whether a stock is overfished. If the stock is expected to be above 1) above its MSY level in `r year` or 2) above ½ of its MSY level in  `r year` and above its MSY level in  `r year+10` under this scenario, then the stock is not overfished.) While Scenario 6 gives the best estimate of OFL for `r year`, it does not provide the best estimate of OFL for `r year + 1`, because the mean `r year` catch under Scenario 6 is predicated on the `r year` catch being equal to the `r year` OFL, whereas the actual `r year` catch will likely be less than the `r year` OFL. The executive summary contains the appropriate one- and two-year ahead projections for both ABC and OFL.

+   *Scenario 7*:  In `r year+1` and `r year+2`, $F$ is set equal to max$F_{ABC}$, and in all subsequent years $F$ is set equal to $F_{OFL}$. (Rationale: This scenario determines whether a stock is approaching an overfished condition. If the stock is 1) above its MSY level in `r year+2` or 2) above 1/2 of its *MSY* level in `r year+2` and expected to be above its MSY level in `r year+12` under this scenario, then the stock is not approaching an overfished condition.)


#### How Future Catches are Specified for Scenario 2 (Author's F) {#authorsF}

> The method for specifying catches in years `r year` to `r year+2` has not changed from the 2021 assessment. 

For Scenario 2 (*Author's F*); we use pre-specified catches to increase accuracy of short-term projections in fisheries where the catch is usually less than the ABC. We specify `r year` catches as the most current observed catches plus the typical landings through the present date through the end of the calendar year, and the catches for years `r year+1` and `r year+2` as the average catch from `r year-5` to `r year-1`, which is `r prettyNum(c2,big.mark=',')` t.

Projected catches, spawning biomass, and fishing mortality rates corresponding to the alternative harvest scenarios over a 13-year period are shown in Tables \@ref(tab:projectionsCatches) through \@ref(tab:projectionsF).
 
## Risk Table and ABC recommendation {#risktable}

The SSC in its December 2018 minutes recommended that all assessment authors use the risk table when determining whether to recommend an ABC lower than the maximum permissible.

The risk table scoring for POP has not changed since 2021, with the exception that the 2021 SSC requested that the number of Risk Table categories (i.e., levels of concern) be reduced from four to three. Per leadership instruction in 2023, we have consolidated what were previously categories 2 and 3 ("substantially increased" and "major concern" into a single category, "increased/major concern"). This impacts the first two considerations, which were rated a level 2 in the 2021 Assessment.

```{r}
l1 = "Level 1: No concern"
l2 = "Level 2: Major concern"
l3 = "Level 3: Extreme concern" 
require(flextable)
data.frame(assess = l2,
           pop = l2,
           enviro = l1,
           fish = l1) %>% 
  flextable() %>% 
    width(j = ~ assess, width = 1.5) %>% 
    width(j = ~ pop, width = 1.5) %>% 
    width(j = ~ enviro, width = 1.5) %>% 
    width(j = ~ fish, width = 1.5) %>% 
    flextable::set_header_labels(level = "",
                    assess = "Assessment-related considerations",
                    pop = "Population dynamics considerations",
                    enviro = "Environmental/ecosystem considerations",
                    fish = "Fishery Performance") %>% 
  flextable::fontsize(size = 10) %>% 
  font(fontname = "Times", part = "all") %>%
    italic(part ='header')
```

An abridged summary of the considerations that led to this determination for each category follows.

### Assessment considerations {#assessmentconsiderations}

The GOA POP assessment model exhibits a strong negative retrospective pattern (spawning biomass continues to increase with new data), though this effect was less pronounced in the 2023, likely due to high uncertainty in the observed survey biomass. This is driven by ongoing increases in the trawl survey biomass, which have been consistently under-estimated since 2013, and may be suggestive of model misspecification. 


*This results in a Level 2 assessment considerations rating, a major concern.*

### Population dynamics considerations

The model estimates above-average recruitment events in the last three decades to account for the increasing survey biomass observations (Figures 10.\@ref(fig:survey), 10.\@ref(fig:biofreccompare) and 10.\@ref(fig:recdevs)).  The estimated recruitment events are still insufficient to satisfactorily fit the recent survey data; these increases are not observed in the early time series nor are they typical for an ecosystem that is warming (with the exception of sablefish). 

The unusual trend of rapid increases in stock size and recruitment estimates *results in a Level 2  population dynamics rating, a major concern.*

### Environmental/Ecosystem considerations
 This year, the GOA ecosystem was characterized by moderate thermal conditions, mixed trends for zooplankton abundance, moderate predation, and increased competition for zooplankton prey resources. The warmer surface waters predicted for 2024 may be favorable for POP larval survival. 
Ecosystem: While optimal temperatures for POP life stages are not known, it is reasonable to expect that the 2023 average ocean temperatures at depth on the shelf edge (for adults) and surface temperatures (for larvae) were adequate for POP.  POP are semi-demersal/pelagic, outer shelf and continental slope (150-420 m depths) dwellers as adults, with a pelagic then inshore benthic juvenile stage (age 1 to 3) in the Gulf of Alaska (GOA) (Carlson and Haight 1976, Love et al. 2002, Rooper and Bolt 2005, Rooper et al. 2007, NPFMC 2010). There is evidence that POP are being observed higher in the water column, potentially a result of an expanding population. As warm spring temperatures are favorable for larval survival (Doyle 2009), cooler spring to above average summer temperatures  varying from 5.8°C (WGOA Bottom Trawl Survey, O’Leary 2023) to 10.5°C (Icy Strait, SEAK, Fergusson 2023) were cooler than optimal, but not considered detrimental. While optimal temperatures are not known for adults, there is no indication of concern given bottom temperatures along the shelf edge in the GOA cooled to average in 2023 (AFSC longline survey: Siwicke 2023). Surface temperatures are predicted to warm in late winter/early spring of 2024, in alignment with El Niño conditions (Bond 2023). These warmer surface temperatures in April/May (larval release) may be favorable for larval survival. As it takes time for warm surface waters to extend to depth, shelf bottom temperatures are not expected to warm in the spring. 

Prey: Planktivorous foraging conditions were average to below average across the GOA in 2023. The primary prey of the adult POP include calanoid copepods, euphausiids, myctophids, and miscellaneous prey in the GOA (Byerly 2001, Yang 2000, Yang 2003). POP body condition increased to average in 2023 after below average condition (i.e. lower weights at length) since 2015 (Bottom Trawl Survey, O’Leary, 2023b). The timing of this declining trend matches the time frame of increasing POP population since the 2014-2016 marine heatwave and could be explained by prey availability and competition within an expanding population. Zooplankton biomass in the WGOA progressed from below average in the spring (lower calanoid copepod biomass and higher euphausiid biomass) to improved conditions in the summer (above average biomass of large calanoid copepods and euphausiids, but continued lower small copepod biomass; Shelikof St., Kimmel 2023, and Seward Line, Hopcroft 2023). Summer planktivorous foraging conditions were somewhat improved with above average large calanoid copepod and euphausiid biomass, but continued lower small copepod biomass (Shelikof, Kimmel 2023). Eastern GOA inside waters had below average total zooplankton biomass, although euphuasiids were above average here as in the western GOA. Planktivorous seabird reproductive success, an indicator of zooplankton availability and nutritional quality, was approximately average south of Kodiak (Chowiet Isl.), and in the central GOA (Middleton Island on shelf edge off Seward) (Drummond 2023, Whelan 2023), and above average in the EGOA (St. Lazaria Isl.).

Predators & Competitors: Predation pressure is considered moderate and competition may have increased in 2023. Predators of juvenile POP include Pacific halibut, arrowtooth flounder, seabirds, rockfish, salmon, and lingcod (Moss 2016). Predators of adults include Pacific halibut, sablefish, and sperm whales (Moss 2016). Halibut and arrowtooth flounder populations remain low relative to previous levels, and, in general, there is no cause to suspect increased predation pressure on larval or adult demersal shelf rockfish. Potential competitors include large returns of pink salmon (Whitehouse, 2023, Vulstek, 2023), a relatively large and increasing population of walleye pollock, other POP as the population continues to increase, and continued large year classes of juvenile sablefish. POP are being found shallower in the water column, increasing their habitat overlap and potential competition for zooplankton prey with walleye pollock. 

The most recent data available *result in a Level 1 ecosystem rating, no apparent concerns.*
 

#### References for Environmental & Ecosystem Considerations

Bond, N. 2023. Seasonal Projections from the National Multi-Model Ensemble (NMME). In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Byerly, M.M. 2001. Ecology of age-1 copper rockfish (*Sebastes caurinus*) in vegetated habitats of Sitka Sound, Alaska. M.S. Thesis. University of Alaska Fairbanks, Juneau, Alaska.

Carlson, H.R., and R.E. Haight. 1976. Juvenile life of Pacific ocean perch, *Sebastes alutus*, in coastal fiords of southeastern Alaska: their environment, growth, food habits, and schooling behavior. Trans. Am. Fish. Soc. 105:191-201.

Danielson, S., and R. Hopcroft. 2023. Ocean temperature synthesis: Seward line may survey. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Doyle, M. J., Picquelle, S. J., Mier, K. L., Spillane, M. C., Bond, N. A. 2009. Larval fish abundance and physical forcing in the Gulf of Alaska, 1981-2003. Prog. Ocean. 80(3-4): 163-187.

Drummond, B., Kettle, A. and Renner, H. 2023. Seabird synthesis: Alaska Maritime National Wildlife Refuge data.  In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Fergusson, E. and Strasburger, W. 2023. Long-term trends in zooplankton densities in Icy Strait, Southeast Alaska. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Fergusson, E. and Strasburger, W. 2023. Ocean temperature synthesis: Southeast Coastal Monitoring Survey. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Hinckley, S., et al. 2019. Connectivity between spawning and nursery areas for Pacific cod (*Gadus macrocephalus*) in the Gulf of Alaska. Deep Sea Research Part II: Topical Studies in Oceanography 165 (2019): 113-126.

Hopcroft, R. 2023. Seward Line: Large Copepod & Euphausiid Biomass. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Kimmel, D., Axler, K., Cormack, B., Crouser, D., Fennie, W., Keister, J., Lamb, J., Pinger, C., Rogers, L., and Suryan, R. 2023. Current and Historical Trends for Zooplankton in the Western Gulf of Alaska. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Love, M.S., M. Yoklavich, and L. Thorsteinson. 2002. The rockfishes of the northeast Pacific. U. of California Press. 405 pp.

Major, Richard L., and Herbert H. Shippen. 1970. Synopsis of biological data on Pacific ocean perch, Sebastodes alutus. FAO Fisheries Synopsis no.79

Monnahan, C.C., Dorn, M.W., Correa, G.M., Deary, A.L., Ferriss, B.E., Levine, M., McGowan, D.W., Rogers, L., Shotwell, S.K., Tyrell, A. and Zador, S. 2023. Assessment of the walleye pollock stock in the Gulf of Alaska. In Stock assessment and fishery evaluation report for the groundfish resources of the Gulf of Alaska, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Morgan, C.A., B.R., Beckman, L.A. Weitkamp, and K.L. Fresh. 2019. Recent ecosystem disturbance in the Northern California Current. Fisheries, 44(10), pp.465-474.

Moss, J. H., et al. 2016. Surviving the Gauntlet: A comparative study of the pelagic, demersal, and spatial linkages that determine groundfish recruitment and diversity in the Gulf of Alaska ecosystem.  NPRB GOA Project G81 Upper Trophic Level Final Report). Anchorage, AK: North Pacific Research Board. NWAFC Processed Rep (2016): 88-21.

NPFMC (North Pacific Fishery Management Council). 2010. Essential Fish Habitat (EFH): 5-year review for 2010, Summary Report. North Pacific Fishery Management Council, 605 W. 4th Ave, suite 306.  Anchorage, AK 99501.

O’Leary, C.  2023a. Ocean temperature synthesis: Bottom trawl survey. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

O’Leary, C. and Rohan, S. 2023b. Gulf of Alaska Groundfish Condition. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Rooper, C.N. , J.L. Boldt, and M. Zimmermann. 2007. An assessment of juvenile Pacific Ocean perch (*Sebastes alutus*) habitat use in a deepwater nursery.  Estuarine, Coastal and Shelf Science 75:371-380

Rooper, C.N. and J.L. Boldt. 2005. Distribution of juvenile Pacific ocean perch *Sebastes alutus* in the Aleutian Islands in relation to benthic habitat. Alaska Fisheries Research Bulletin 11(2):102-112.

Siwicke, K. 2023. Ocean temperature synthesis: Longline survey. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Vulstek, S., Russell, J. R. 2023. Trends in survival of coho, sockeye, and pink salmon from Auke Creek, Southeast Alaska. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Whelan, S., Hatch, S.A., Arimitsu, M., and Piatt, J.F. 2023. Seabird breeding performance on Middleton Island. In Ferriss, B., 2023. Ecosystem Status Report 2023: Gulf of Alaska, Stock Assessment and Fishery Evaluation Report, North Pacific Fishery Management Council, 1007 West Third, Suite 400, Anchorage, Alaska 99501.

Yang, M., and M.W. Nelson. 2000. Food habits of the commercially important groundfishes in the Gulf of Alaska in 1990, 1993, and 1996. U. S. Dep. Commer. NOAA Tech. Memo. NMFS-AFSC- 112, 174 p.

Yang, M-S. 2003. Food habits of important groundfishes in the Aleutian Islands in 1994 and 1997. U.S. Dep. Commer., AFSC Processed Report 203-07., 233 p.
 


### Fishery performance

There have been no recent changes to spatial distribution of catch, percent of TAC taken, or fishing duration. There are no indications of adverse signals or concerns about the fishery in terms of resource-use, performance, or behavior.  

*Fishery Performance for POP is scored as Level 1 (normal concern)*.
 
### Risk Table Summary and ABC recommendation
 
*We do not recommend a reduction in ABC because the retrospective pattern in this assessment indicates an increasing population abundance, and the population is well above $B_{40\%}$.* We acknowledge that the current assessment model does not appropriately explain these dynamics at present.

### Status Determination

> The status definitions under the MSFCMA have been truncated from this report. 

#### Overfishing 

The official catch estimate for the most recent complete year (`r year-1`) is `r prettyNum(c0,big.mark=",")` t. This is less than the `r year-1` OFL of `r prettyNum(45580,big.mark=",")` t. *The stock is not subject to overfishing.*

#### Overfished (Harvest Scenario 6)

The minimum stock size threshold (MSST) for POP is given by the $B_{35\%}$ which is `r prettyNum(b35_25,big.mark=",")` in `r year`. The estimated stock spawning biomass in `r year` is nearly double the MSST at `r prettyNum(ssb_25,big.mark=",")`. *The stock is not overfished*.

#### Approaching Overfished (Harvest Scenario 7)

The mean estimated stock spawning biomass in `r year+2` is above the MSST. *The stock is not approaching an overfished state*.





