# Ecosystem Considerations

> Operational Update: The Ecosystem Considerations for BSAI FHS are unchanged. The reader is referred to the last full assessment [@Monnahan2020] for the entirety of this section, which has been summarized below.  

In general, a determination of ecosystem considerations for BSAI FHS is hampered by the lack of biological and habitat information.

## Ecosystem Effects on the Stock

**Prey availability/abundance trends**: Results from an Ecopath-like model (Aydin et al., 2007) based on stomach content data collected in the early 1990’s indicate that flathead sole occupy an intermediate trophic level in the eastern Bering Sea ecosystem (Figure 9.40). They feed upon a variety of species, including juvenile walleye pollock and other miscellaneous fish, brittlestars, polychaetes, and crustaceans (Figure 9.41). The proportion of the diet composed of fish appears to increase with flathead sole size (Lang et al., 2003). The 2017 pollock assessment estimated high recruitment in 2014 and 2015 (Ianelli et al. 2017). Information about the abundance trends of the benthic infauna of the Bering Sea shelf is sparse, although some benthic infauna are caught in the EBS groundfish trawl survey. The original description of infaunal distribution and abundance by Haflinger (1981) resulted from sampling conducted in 1975 and 1976 and has not been re-sampled since. 
McConnaughy and Smith (2000) compared the diet between areas with high survey CPUE to that in areas with low survey CPUE for a variety of flatfish species. For flathead sole, the diet in high CPUE areas consisted largely of echinoderms (59% by weight; mostly ophiuroids), whereas 60% of the diet in the low CPUE areas consisted of fish, mostly pollock. These areas also differed in sediment types, with the high CPUE areas consisting of relatively more mud than the low CPUE areas. McConnaughy and Smith (2000) hypothesized that the substrate-mediated food habits of flathead sole were influenced by energetic foraging costs. 


**Predator population trends**: The dominant predators of adult flathead sole are Pacific cod and walleye pollock (Figure 9.42). Pacific cod, along with skates, also account for most of the predation upon flathead sole less than 5 cm (Lang et al. 2003). Arrowtooth flounder, Greenland turbot, walleye pollock, and Pacific halibut comprised other predators. Flathead sole contributed a relatively minor portion of the diet of skates from 1993-1996, on average less than 2% by weight, although flatfish in general comprised a more substantial portion of skates greater than 40 cm. A similar pattern was seen with Pacific cod, where flathead sole generally contribute less than 1% of the cod diet by weight, although flatfish in general comprised up to 5% of the diet of cod greater than 60 cm. In 2017 the survey biomass for EBS Pacific cod declined by 46%, the largest decline of Pacific cod in the history of the survey (Thompson et al. 2017). A survey extension to the Northern Bering Sea (NBS) showed a substantial increase in NBS Pacific cod in 2017 from the previous NBS survey in 2010. The NBS survey was completed again in 2018 and showed a high level of Pacific cod in the region. Recent genetics work (pers. comm. Spies) showed that the cod found in the EBS shelf and NBS surveys cannot be distinguished genetically. See the EBS Pacific cod assessment within this SAFE report for more information. Survey biomass of skates in the Bering Sea has been increasing since 2011 (Ormseth 2016, Ormseth 2017). There is a large amount of uncertainty concerning predation on flathead sole; almost 80% of the mortality that flathead sole experience is from unexplained sources (Figure 9.42).  There is some evidence of cannibalism for flathead sole. Stomach content data collected from 1990 indicate that flathead sole were the most dominant predator, and cannibalism was also noted in 1988 (Livingston et al. 1993). 

**Changes in physical environment**: The habitats occupied by flathead sole are thought to be influenced by temperature or the extent of sea ice, which has shown considerable variation in the eastern Bering Sea in recent years. For example, the timing of spawning and advection to nursery areas are expected to be affected by environmental variation. Flathead sole spawn in deeper waters near the margin of the continental shelf in late winter/early spring and migrate to their summer distribution of the mid and outer shelf in April/May. The distribution of flathead sole, as inferred by summer trawl survey data, has been variable. In 1999, one of the coldest years in the eastern Bering Sea, the distribution was shifted further to the southeast than it was during 1998-2002. Bottom temperatures during the 2006-2010 and 2012-2013 summertime EBS Trawl Surveys were colder than average. 2018 was the warmest year recorded in the EBS shelf trawl survey and the only year in the history of the survey in which no cold pool was observed (i.e. no temperatures below 2 deg C were recorded at any survey station). Further exploration of flathead sole behavior in relation to the cold pool is needed. If flathead sole move to avoid the cold pool, there may be an increase in flathead sole habitat with loss of sea ice.
In the 2010 NBS survey, no flathead sole were found in the northern Bering Sea area, but a substantial abundance of Bering flounder was found. Bering flounder biomass in the northern Bering Sea area was estimated at 12,761 t, larger than that in the standard survey area (12,360 t). This is consistent with the view that Bering flounder in the BSAI fishery are a marginal stock on the edge of their species range in the eastern Bering Sea.  Potential management implications of the northern Bering Sea survey for Bering flounder based on the 2010 NBS survey were discussed in more detail in Appendix C of the 2010 SAFE document (Stockhausen et al., 2010). 
Survey biomass of flathead sole in the 2017 and 2018 NBS was 83 t and 510 t, respectively, and Bering flounder survey biomass was 20,712 t and 30,025 t. No genetics work has been done to date to determine if the flathead sole in the NBS are genetically the same as the flathead sole in the EBS, or if Bering flounder and flathead sole found in these areas are actually different species. Future assessments may need to incorporate the data from the NBS.

**Fishery Effects on the Ecosystem**: Table 9.23-Table 9.26 show the contribution of fishing targeting flathead sole on non-target species and prohibited species catch. In 2020, the flathead sole fishery in the BSAI contributed 0-12% of the catch of any nontarget species. Table 9.25 shows the contribution of the directed flathead sole fishery to prohibited species catch estimates as a proportion of all prohibited species catch for each species. The flathead sole fishery caught 21% of Opilio tanner (snow) crab and 24% of Bairdi tanner crab in 2020. 
Table 9.26 shows that the proportion of BSAI halibut mortality as PSC that occurred in the directed flathead sole fishery was at 8% in 2019 and 2.5% in 2020 of the halibut mortality as PSC from all fisheries in the BSAI.

