\newpage

# Tables

```{r commcatch}
catch <- read.csv(here::here(year,'safe','static_tables','catch_abc_tac_ofl_mgmt.csv'))
catch$Year<-as.character(catch$Year)
flextable::regulartable(catch) %>%
  flextable::set_caption("Total catch, ABC, Final TAC, OFL, and associated management measures for BSAI FHS since 2007. The Total column are the catches used in the assessment and projection model. Catch at age and length are provided in separate tables. Catch Accounting System via AKFIN database.")%>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all") %>% flextable::set_header_labels( values = c('Year',
                                             'Total Catch (t)',
                                             'ABC',
                                             'TAC',
                                             'OFL','Management Measures')) 
```

\pagebreak

```{r fishlengthcompstF} 
flextable::regulartable(mod18.2c_2024$lendbase %>%
                          filter(Fleet ==1 & sex == 1 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostlendbase$Yr[mod18.2c_2024$ghostlendbase$Fleet==1]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Length (cm)' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Length (cm)',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Fishery length frequency data for female BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:7,digits = 4) %>%
  flextable::compose(i = 24, j = 1, flextable::as_paragraph('58+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")

```

\pagebreak

```{r fishlengthcompstM} 
flextable::regulartable(mod18.2c_2024$lendbase %>%
                          filter(Fleet ==1 & sex == 2 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostlendbase$Yr[mod18.2c_2024$ghostlendbase$Fleet==1]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Length (cm)' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Length (cm)',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Fishery length frequency data for male BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:7,digits = 4) %>%
  flextable::compose(i = 24, j = 1, flextable::as_paragraph('58+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")

```

\pagebreak

```{r fishagecompstF}
flextable::regulartable(mod18.2c_2024$agedbase %>%
                          filter(Fleet ==1 & sex == 1 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostagedbase$Yr[mod18.2c_2024$ghostagedbase$Fleet==1]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Age' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Age',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Fishery age frequency data for female BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:17,digits = 4) %>%
  flextable::compose(i = 21, j = 1, flextable::as_paragraph('21+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")

```
\pagebreak

```{r fishagecompstM}
flextable::regulartable(mod18.2c_2024$agedbase %>%
                          filter(Fleet ==1 & sex == 2 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostagedbase$Yr[mod18.2c_2024$ghostagedbase$Fleet==1]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Age' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Age',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Fishery age frequency data for male BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:17,digits = 4) %>%
  flextable::compose(i = 21, j = 1, flextable::as_paragraph('21+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")
```

\pagebreak

```{r survobs}
flextable::regulartable(mod18.2c_2024$cpue %>%
                          dplyr::mutate( Year = as.character(Yr)) %>%
                          dplyr::select(Year, 'Biomass (t)' = Obs, SE)) %>%
  flextable::set_caption("Survey biomass estimates (t) with standard error (SE) for BSAI FHS.") %>%
  flextable::colformat_double(j = 3, digits = 2) %>%
  flextable::colformat_double(j = 2, big.mark =',') %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")
```

\pagebreak

```{r survlengthcompsF} 
flextable::regulartable(mod18.2c_2024$lendbase %>%
                          filter(Fleet == 2 & sex == 1 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostlendbase$Yr[mod18.2c_2024$ghostlendbase$Fleet==2]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Length (cm)' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Length (cm)',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Survey length frequency data for female BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:7,digits = 4) %>%
  flextable::compose(i = 24, j = 1, flextable::as_paragraph('58+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")

```

\pagebreak


```{r survlengthcompsM} 
flextable::regulartable(mod18.2c_2024$lendbase %>%
                          filter(Fleet == 2 & sex == 2 & Yr > 2000 & !(Yr %in% unique(mod18.2c_2024$ghostlendbase$Yr[mod18.2c_2024$ghostlendbase$Fleet==2]))) %>%
                          mutate(effN = round(effN,1),
                                 Obs = round(Obs, 4)) %>%
                          select(Yr, effN,'Length (cm)' = Bin, Obs ) %>%  
                          tidyr::pivot_wider(
                            id_cols = 'Length (cm)',
                            names_from = c(Yr,effN),
                            names_glue = "{Yr} ({effN})",
                            values_from = Obs)) %>%
  flextable::set_caption("Survey length frequency data for male BSAI FHS since 2000 used in the model. Input sample sizes are in parentheses.") %>%
  flextable::colformat_double(j = 2:7,digits = 4) %>%
  flextable::compose(i = 24, j = 1, flextable::as_paragraph('58+')) %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 11, part = "all")

```

\pagebreak

```{r parposteriorst}

flextable::flextable(
  mod18.2c_2024$parameters %>%
    filter(!(grepl('RecrDev', Label))) %>%
    select(Label, Value, Parm_StDev, Phase) %>%
    mutate('Purpose' = c(rep('Growth, Mortality and Maturity',20),
                         rep('Recruitment',7),
                         rep("Initial Conditions and Scale",4),
                         rep("Fishery Size Selectivity",5),
                         rep("Survey Age Selectivity",6),
                         rep("Survey Age Selectivity (Male Offset)",5),
                         rep("Fishery Size Selectivity (Time Blocking)",4)),
           
           lci= prettyNum(Value-1.96*Parm_StDev, big.mark = ',', digits = 3),
           uci = prettyNum(Value+1.96*Parm_StDev, big.mark = ',', digits = 3),
           MLE = prettyNum(Value, big.mark = ',', digits = 3),
           Interval0 = paste(lci,uci, sep = '-'),
           Interval = ifelse(Interval0== 'NA-NA','',Interval0),
           'Fixed/Estimated' = ifelse(Phase<0,'Fixed','Estimated')) %>%
    select( Purpose, Label,  'Fixed/Estimated',MLE ,  Interval))  %>%
  # flextable::colformat_double(j = 4, digits = 3) %>%
   flextable::width(j = 1, width = 2.5, unit = 'in') %>%
  flextable::width(j = 2, width = 0.5, unit = 'in') %>%
    flextable::width(j = 5, width = 1, unit = 'in') %>%
    flextable::set_header_labels( values = c('Purpose',
                                             'Estimated parameter',
                                             'Treatment',
                                             'MLE',
                                             '95% Interval')) %>%
      flextable::set_caption("All parameters from the base model, with 95% credible intervals.") %>%
    flextable::font(fontname = "Times New Roman", part = "all") %>%
    flextable::fontsize(size = 11, part = "all")
```

\pagebreak


```{r timeseriest}

totbio <- mod18.2c_2024$timeseries %>%
  mutate(Label2 = 'TotBio',
         value = prettyNum(Bio_smry, big.mark = ',',digits = 3),
         Interval = '')%>%
   select(Year=Yr, Label=Label2, value)%>%
  tidyr::pivot_wider(id_cols = c(Year), names_from = Label, values_from = value)
  
recruitment <- mod18.2c_2024$recruit %>%
  mutate(Label2 = 'Recruitment',
     lci= prettyNum(ifelse(pred_recr-exp(dev)*pred_recr<0,0, pred_recr-exp(dev)*pred_recr), big.mark = ',', digits = 3),
         uci = prettyNum(pred_recr+exp(dev)*pred_recr, big.mark = ',', digits = 3),
         MLE = prettyNum(pred_recr, big.mark = ',', digits = 3),
         Interval0 = paste(lci,uci, sep = '-'),
         Interval = ifelse(Interval0== 'NA-NA','',Interval0),
         value = paste0(MLE, " (", Interval,")")) %>%
   select(Year=Yr, Label=Label2, value)%>%
  tidyr::pivot_wider(id_cols = c(Year), names_from = Label, values_from = value)

timeseries <- mod18.2c_2024$derived_quants  %>%
                          
  mutate(Label2 = stringr::str_extract(Label, "^[^_]*"),
         Year = stringr::str_extract(Label,  "(?<=\\_).*"),
         lci= prettyNum(Value-1.96*StdDev , big.mark = ',', digits = 3),
         uci = prettyNum(Value+1.96*StdDev , big.mark = ',', digits = 3),
         MLE = prettyNum(Value, big.mark = ',', digits = 3),
         Interval0 = paste(lci,uci, sep = '-'),
         Interval = ifelse(Interval0== 'NA-NA','',Interval0),
         value = paste0(MLE, " (", Interval,")")) %>%
  select(Year, Label=Label2, value) %>%
  filter(Label %in% c('SSB','Bratio','F')) %>%
  tidyr::pivot_wider(id_cols = c(Year), names_from = Label, values_from = value) %>%
  merge(., recruitment, by = 'Year') %>%
  merge(totbio, by = 'Year')

flextable::regulartable(timeseries %>%
                          select(Year, SSB, TotBio, Bratio, 'F', Recruitment)) %>%
  flextable::set_caption("Estimated time series of female spawning biomass, total biomass,  fully-selected fishing mortality rate, age 0 Recruitment, for BSAI FHS. Values shown are the median and 95% confidence intervals (parentheses); these are not available for total biomass.") %>%
  flextable::set_header_labels(values = c('Year',
                                          'Spawning Biomss (kt)',
                                          'Total (3+) Biomass (kt)',
                                          'Stock Depletion',
                                          'Fully Selected F',
                                          'Age 0 Recruits (millions)')) %>%
  flextable::width(j = c(2,5:6), width = 1.75, unit = 'in') %>%
  flextable::width(j = c(4), width = 1.5, unit = 'in') %>%
  flextable::width(j = 3, width = 1, unit = 'in') %>%
  # flextable::width(j = 1, width = 0.25, unit = 'in') %>%
  flextable::font(fontname = "Times New Roman", part = "all") %>%
  flextable::fontsize(size = 9, part = "all")
```

\pagebreak

```{r resultscompare}

# (Results) Tier 1-3: Estimated recruitment time series with the avg of year classes spawned after 1976  **- render from SS3**
# read.csv(here::here(year, 'mgmt', model,'processed','parameter_summary.csv')) %>%
#   mutate(src = '2023 Model')%>%
#   merge(.,read.csv(here::here(year, 'base','processed','parameter_summary.csv')) %>%
#           mutate(src = '2021 Model'), by = 'variable')  %>%
#   mutate(value = paste0(round(median.x,2), " (",round(median.y,2),")")) %>%
#   select('Likelihood Component/Parameter' = Parameter.x, '2023 Value (2021 Value)' =value) %>%
#   bind_rows(., 
#             
#             read.csv(here::here(year, 'mgmt', model,'processed','likelihoods.csv')) %>%
#               mutate(src = '2023 Model')%>%
#               merge(.,read.csv(here::here(year, 'mgmt','2020.1-2021','processed','likelihoods.csv')) %>%
#                       mutate(src = '2021 Model'), by = 'variable')  %>%
#               mutate(value = paste0(round(value.x,2), " (",round(value.y,2),")")) %>%
#               filter(!(variable %in% c("Fishery CPUE Likelihood",
#                                        "Alternative Survey Abundance Index Likelihood",
#                                        "Bottom Trawl Survey Size Composition Likelihood",
#                                        "Alternative Survey Size Composition Likelihood",
#                                        "Priors q Alternative Survey"))) %>%
#               select('Likelihood Component/Parameter' = variable, '2023 Value (2021 Value)' =value))  %>%
#   
#   flextable::flextable(.) %>%
#   flextable::width(j = 1, width = 3.5, unit = 'in') %>%
#     flextable::width(j = 2, width = 2.75, unit = 'in') %>%
#       flextable::set_caption("Comparison of median parameter estimates (from MCMC) and likelihood component scores from the base model and the 2021 model (shown in parentheses). The MLE for sigma R is 0.764 in the base model and 0.771 in the 2021 model; that parameter is fixed for MCMC analyses.") %>%
# flextable::font(fontname = "Times New Roman", part = "all") %>% 
#   flextable::fontsize(size = 11, part = "all")  
```

\pagebreak

```{r projectionsCatches}
# proj_temp <- read.csv(here::here(year,'mgmt','2020.1-2023','processed','mscen_yld.csv'))
# proj_temp$year <- as.character(proj_temp$year)
# proj_temp[,2:8] <- sapply(proj_temp[,2:8], FUN = function(x) prettyNum(round(x),big.mark = ','))
# names(proj_temp) <- c("Year",	"Maximum permissible F",	"Author’s F* (pre-specified catch)",	"Half maximum F",	"5-year average F",	"No fishing",	"Overfished",	"Approaching overfished")
# flextable::regulartable(proj_temp) %>%  
#   flextable::set_caption("Table of 13-year projected catches corresponding to the alternative harvest scenarios, using stochastic methods if possible (mean values or other statistics may be shown in the case of stochastic recruitment scenarios). This set of projections encompasses six harvest scenarios designed to satisfy the requirements of Amendment 56, the National Environmental Protection Act, and the Magnuson-Stevens Fishery Conservation and Management Act (MSFCMA). For a description of scenarios see Projections and Harvest Alternatives. All units in t.")%>%
#   flextable::font(fontname = "Times New Roman", part = "all") %>% 
#   flextable::width(j = 1, width = 0.5, unit = 'in') %>% 
#   flextable::fontsize(size = 10, part = "all")
```

\pagebreak

```{r projectionsSsb}
# proj_temp <- read.csv(here::here(year,'mgmt','2020.1-2023','processed','mscen_ssb.csv'))
# proj_temp$year <- as.character(proj_temp$year)
# proj_temp[,2:8] <- sapply(proj_temp[,2:8], FUN = function(x) prettyNum(round(x),big.mark = ','))
# names(proj_temp) <- c("Year",	"Maximum permissible F",	"Author’s F* (pre-specified catch)",	"Half maximum F",	"5-year average F",	"No fishing",	"Overfished",	"Approaching overfished")
# flextable::regulartable(proj_temp) %>%  
#   flextable::set_caption("Table of 13-year projected spawning biomass corresponding to the alternative harvest scenarios, using stochastic methods if possible (mean values or other statistics may be shown in the case of stochastic recruitment scenarios). This set of projections encompasses six harvest scenarios designed to satisfy the requirements of Amendment 56, the National Environmental Protection Act, and the Magnuson-Stevens Fishery Conservation and Management Act (MSFCMA). For a description of scenarios see Projections and Harvest Alternatives. All units in t.")%>%
#    flextable::font(fontname = "Times New Roman", part = "all") %>% 
#   flextable::width(j = 1, width = 0.5, unit = 'in') %>%
#   flextable::fontsize(size = 10, part = "all")
```

\pagebreak

```{r projectionsF}
# proj_temp <- read.csv(here::here(year,'mgmt','2020.1-2023','processed','mscen_f.csv'))
# proj_temp$year <- as.character(proj_temp$year)
# proj_temp[,2:8] <- sapply(proj_temp[,2:8], FUN = function(x)  format(round(as.numeric(x), 2), nsmall = 3))
# names(proj_temp) <- c("Year",	"Maximum permissible F",	"Author’s F* (pre-specified catch)",	"Half maximum F",	"5-year average F",	"No fishing",	"Overfished",	"Approaching overfished")
# flextable::regulartable(proj_temp) %>%  
#   flextable::set_caption("Table of 13-year projected fishing mortality rates corresponding to the alternative harvest scenarios, using stochastic methods if possible (mean values or other statistics may be shown in the case of stochastic recruitment scenarios). This set of projections encompasses six harvest scenarios designed to satisfy the requirements of Amendment 56, the National Environmental Protection Act, and the Magnuson-Stevens Fishery Conservation and Management Act (MSFCMA). For a description of scenarios see Projections and Harvest Alternatives. All units in t.")%>%
#   flextable::font(fontname = "Times New Roman", part = "all") %>% 
#   flextable::width(j = 1, width = 0.5, unit = 'in') %>%
#   flextable::fontsize(size = 10, part = "all")
```


