---
params: 
  chapter: 9
  species: "Flathead sole-Bering Flounder stock Complex"
  species_complex: "no"
  area: "Bering Sea and Aleutian Islands"
  tier: 3
author: "Maia S. Kapur, Lee Cronin-Fine"
date: "November 2024"

# don't do anything below this line unless you are cool with the consequences
output:
  bookdown::word_document2:
     reference_docx: "template.docx"
     toc: false
     number_sections: false
     css: "styles.css"
     pandoc_args:  
       - '--lua-filter=scholarly-metadata.lua'
       - '--lua-filter=author-info-blocks.lua'

always_allow_html: true        
fontsize: 11pt
geometry:
  - top=1in
  - bottom=1in
  - left=1in
  - right=1in     
fig_caption: true
bibliography: "safe_bibby.bib"
csl: "fishfish.csl"

---

This report may be cited as:
Kapur, M.S., Cronin-Fine, L. 2024. Assessment of the flathead sole-Bering flounder stock complex in the Bering Sea and Aleutian Islands. North Pacific Fishery Management Council, Anchorage, AK. Available from https://www.npfmc.org/library/safe-reports/
  
```{r setup, include=FALSE, echo = FALSE}
# remotes::install_github("crsh/rmdfiltr")
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "!h", out.extra = "")
knitr::opts_knit$set(eval.after = "fig.cap")
x = 1
sprintf("Figure %s. " , paste0(params$chapter, '.',x))
```

```{r, include=FALSE, echo = FALSE}
if(params$species_complex=="no"){
   title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock in the ", params$area)
  } else {
    title = paste0(params$chapter, ". Assessment of the ", tools::toTitleCase(params$species), " Stock Complex in the ", params$area)  
  } 
```

---
title: `r title`
---

```{r load, warning=F, message=F, echo = FALSE}
# load
library(safe)
library(here)
library(dplyr)
# globals 
species <- params$species
year <- 2024
date <- 'October XX, 2024'
model <- '18.2c_2024'
model_name <- "Model 18.2c (2024)"
old_model_name <- "Model 18.2c (2020)"
mod_path <- here::here(year,'mgmt',model)
mod18.2c_2024 <- r4ss::SS_output(mod_path, verbose = FALSE, warn = FALSE, printstats = FALSE, hidewarn = TRUE)
names(mod18.2c_2024$timeseries)[23] <- "F1" ## overwrite so inline works
end_proj <- year + 15

## read in exec summ and assign derived quants; these get populated in doc
execsumm <-  read.csv(here::here(year,'model_runs','03b_projection','2024-05-30-exec_summ.csv'))[,2:3]
ofl_25 <- round(execsumm[9,1]) ## ofl in mt
Fofl_25 <- round(execsumm[6,1],2)
Fabc_25 <- round(execsumm[7,1],2)
b0_25 <- round(execsumm[3,1]) ## unfished ssb, invariant across time
b40_25 <- execsumm[4,1] ## biomass at abc
b35_25 <-  execsumm[5,1]  # aka MSST or biomass at ofl
ssb_25 <- execsumm[2,1] # 2025 spawning biomass
tb_25 <- execsumm[1,1] # 2025 total biomass
abc_23 <- 68203; abc_23p <- prettyNum(abc_23,big.mark=',') ## 2023 model's ABC for 2025 FROM FEDERAL REGISTER 
abc_25 <- round(execsumm[10,1]) ## this year's ABC for 2025 

## catch in 2023, y-1 (in model)
c0 <- mod18.2c_2024$catch %>% filter(Yr == 2023) %>% select(Obs) %>% as.numeric()

## catches used in projection            
pcatch <- readLines(here::here(year,'model_runs','03b_projection','spm.dat'))[54:56] %>%
  strsplit(.,'\t') %>% ## split at tabs
  unlist() %>%
  strsplit(.,' +') %>% ## split at spaces 
  unlist()
pcatch<- round(as.numeric(pcatch[c(2,4,6)]))

c1 <- pcatch[1] # estimated catch in current year
c2 <- pcatch[2] # proj catch year + 1
c3 <- pcatch[3] # proj catch year + 2

# Best F (for SARA files & stock status section) ----
# Use this year's model to recalculate the F for the previous year 
## that would have produced the specified OFL for the previous year
# provide naa, waa, etc from terminal year of model - can rip from Proj
projdat <- readLines(here::here(year,'model_runs','03b_projection', "projection_data.dat"))
ages <- 1:as.numeric(unlist(strsplit(projdat[grep("number of ages", projdat)]," "))[1])
naa_f <-  as.numeric(unlist(strsplit(projdat[29]," "))[ages])
naa_m <- as.numeric(unlist(strsplit(projdat[30]," "))[ages])
waa_f <- as.numeric(unlist(strsplit(projdat[23]," "))[ages])  ## fishery WAA
waa_m <- as.numeric(unlist(strsplit(projdat[24]," "))[ages])
saa_f <- waa_f <- as.numeric(unlist(strsplit(projdat[26]," "))[ages])
saa_m <- waa_f <- as.numeric(unlist(strsplit(projdat[27]," "))[ages])
mort <-  as.numeric(unlist(strsplit(projdat[14]," "))[ages])

ofl_23_23 <- 48161 ## last model's OFL for last year (2023 model for 2023 https://www.npfmc.org/wp-content/PDFdocuments/SAFE/2023/GOAflathead.pdf)
afscassess::best_f(data = data.frame(age = ages, 
                                     naa1 = naa_f,
                                     naa2 = naa_m,
                                     waa1 = waa_f,
                                     waa2 = waa_m,
                                     saa1 = saa_f,
                                     saa2 = saa_m),
                   m = mort, m2 = mort,
                   type = 3, ## two sex, one year
                   f_ratio= NULL, ## only one gear
                   last_ofl = ofl_23_23, 
                   last_f = 0.1
                   ) %>%
  strsplit(., " ") %>%
  unlist() %>%
  last(.) %>%
  as.numeric() %>%
  round(.,3) -> f_best
```

 
 
 
 
```{r, child="01-summary.Rmd", eval = T}
```

```{r, child="02-responses.Rmd", eval = T}
```

```{r, child="03-intro-update.Rmd", eval = T}
```

```{r, child="04-fishery-update.Rmd", eval = T}
```

```{r, child="05-data-update.Rmd", eval = T}
```

```{r, child="06-model-update.Rmd", eval = T}
```

```{r, child="07-results-update.Rmd", eval = T}
```

```{r, child="08-abc.Rmd", eval = T}
```

```{r, child="09-ecosystem.Rmd", eval = T}
```

```{r, child="10-gaps.Rmd", eval = T}
```

\pagebreak

\allsectionsfont{\centering}
# References
<div id="refs"></div>


```{r, child="11a-auxiliaryfiles.Rmd", eval = T}
```

```{r, child="11-tables-update.Rmd", eval = T}
```

```{r, child="12-figures-update.Rmd", eval = T}
```
 

